require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/claims", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Claim. As you add validations to Claim, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryBot.create(:claim) 
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ClaimsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }


  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Claim" do
        expect {
          post 'api/v1/tickets/1/claim',
               params: { claim: valid_attributes }, as: :json
        }.to change(Claim, :count).by(1)
      end

      it "renders a JSON response with the new claim" do
        post claims_url,
             params: { claim: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Claim" do
        expect {
          post claims_url,
               params: { claim: invalid_attributes }, as: :json
        }.to change(Claim, :count).by(0)
      end

      it "renders a JSON response with errors for the new claim" do
        post claims_url,
             params: { claim: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested claim" do
   
      expect {
        delete claim_url(valid_attributes), headers: valid_headers, as: :json
      }.to change(Claim, :count).by(-1)
    end
  end
end
